[package]
name = "koto_bytecode"
version = "0.16.0"
description = "The bytecode compiler used by the Koto programming language"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[features]
default = ["rc", "num64"]

# Only one memory management strategy can be enabled at a time.
# To use `arc`, default features must be disabled.
arc = ["koto_memory/arc"]
rc = ["koto_memory/rc"]

# Only one number bit width can be enabled at a time
# To use 'num32', default features must be disabled
num64 = ["koto_parser/num64"]
num32 = ["koto_parser/num32"]

[package.metadata.cargo-feature-requirements]
rc = { requires = ["!arc"] }
arc = { requires = ["!rc"] }
num64 = { requires = ["!num32"] }
num32 = { requires = ["!num64"] }

[dependencies]
koto_memory = { path = "../memory", version = "^0.16.0", default-features = false }
koto_parser = { path = "../parser", version = "^0.16.0", default-features = false }

circular-buffer = { workspace = true }
derive-name = { workspace = true }
dunce = { workspace = true }
rustc-hash = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
