[package]
name = "koto"
version = "0.16.0"
description = "A simple, expressive, embeddable programming language"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[features]
default = ["rc", "num64"]

# Only one memory management strategy can be enabled at a time.
# To use `arc`, default features must be disabled.
rc = ["koto_runtime/rc"]
arc = ["koto_runtime/arc"]

# Only one number bit width can be enabled at a time
# To use 'num32', default features must be disabled
num64 = ["koto_bytecode/num64", "koto_parser/num64", "koto_runtime/num64"]
num32 = ["koto_bytecode/num32", "koto_parser/num32", "koto_runtime/num32"]

[package.metadata.cargo-feature-requirements]
rc = { requires = ["!arc"] }
arc = { requires = ["!rc"] }
num64 = { requires = ["!num32"] }
num32 = { requires = ["!num64"] }

[dependencies]
koto_bytecode = { path = "../bytecode", version = "^0.16.0", default-features = false }
koto_parser = { path = "../parser", version = "^0.16.0", default-features = false }
koto_runtime = { path = "../runtime", version = "^0.16.0", default-features = false }

thiserror = { workspace = true }

[dev-dependencies]
koto_geometry = { path = "../../libs/geometry", default-features = false }
koto_test_utils = { path = "../test_utils", default-features = false }

anyhow = { workspace = true }
criterion2 = { workspace = true }
dunce = { workspace = true }
mimalloc = { workspace = true }

[[bench]]
name = "koto_benchmark"
harness = false
test = true
