[package]
name = "koto_serialize"
version = "0.16.0"
description = "Serde serialization support for the Koto programming language"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[features]
default = ["rc", "num64"]

# Only one memory management strategy can be enabled at a time.
# To use `arc`, default features must be disabled.
rc = ["koto_runtime/rc"]
arc = ["koto_runtime/arc"]
num64 = ["koto_runtime/num64"]
num32 = ["koto_runtime/num32"]

[package.metadata.cargo-feature-requirements]
rc = { requires = ["!arc"] }
arc = { requires = ["!rc"] }
num64 = { requires = ["!num32"] }
num32 = { requires = ["!num64"] }

[dependencies]
serde = { workspace = true }

[dependencies.koto_runtime]
path = "../../crates/runtime"
version = "^0.16.0"
default-features = false
